/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Random;
public class Library {
    public int[] roll(int n) {
        Random rand = new Random();
        int[] rolls = new int[n];

        for (int i = 0; i < rolls.length; i++) {
            //nextInt method returns value between 0 (inclusive) and specified bound (exclusive). For 1 - 6:
            int roll = rand.nextInt(6) + 1;
            rolls[i] = roll;
        }
        return rolls;
    }
}
