/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Restaurant extends Destination{
    // Constructor
     public Restaurant(String name, int priceCategory) {
        super(name, priceCategory);
    }
}
