/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Review {
    private String author;
    private int stars;
    private String body;
    private Restaurant restaurant;

    public Review(String author, int stars, String body, Restaurant restaurant) {
        this.author = author;

        // Limit the stars to between 1 and 5
        if (stars < 1 || stars > 5) {
            throw new IllegalArgumentException("Stars must be between 1 and 5");
        }

        this.stars = stars;
        this.body = body;
        this.restaurant = restaurant;
        restaurant.addReview(this);
    }

    @Override
    public String toString() {
        return String.format("Review { author: \"%s\", stars: %d, body: \"%s\" }", this.author, this.stars, this.body);
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public int getStars() {
        return stars;
    }

    public void setStars(int stars) {
        this.stars = stars;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public Restaurant getRestaurant() {
        return restaurant;
    }
}
