/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class TheaterReview extends Review {
    // Fields
    private String movieTitle = "";

    // Constructors
    public TheaterReview(String author, int stars, String body, Theater theater) {
        super(author, stars, body, theater);
    }

    public TheaterReview(String author, int stars, String body, Theater theater, String movieTitle) {
        super(author, stars, body, theater);
        this.movieTitle = movieTitle;
    }

    //Methods
    @Override
    public String toString() {
        if (movieTitle.isEmpty()) {
            return String.format("TheaterReview { author: \"%s\", stars: %d, body: \"%s\" }", this.getAuthor(), this.getStars(), this.getBody());
        } else {
            return String.format("TheaterReview { author: \"%s\", stars: %d, movieTitle: \"%s\", body: \"%s\" }", this.getAuthor(), this.getStars(), this.getMovie(), this.getBody());
        }

    }

    // Getters and Setters
    public String getMovie() {
        return movieTitle;
    }

    public void setMovieTitle(String movieTitle) {
        this.movieTitle = movieTitle;
    }
}
