/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ReviewTest {
    // Declaring ANSI_GREEN to color the successful test souts :)
    public static final String ANSI_GREEN = "\u001B[32m";
    // Declaring ANSI_RESET so that we can reset the color
    public static final String ANSI_RESET = "\u001B[0m";

    @Test
    public void testConstructor() {
        Review classUnderTest = new Review("Mr. Critic", 5, "Tasty burritos and sandwiches!");
        assertEquals("Tasty burritos and sandwiches!", classUnderTest.getBody());
        assertEquals("Mr. Critic", classUnderTest.getAuthor());
        assertEquals(5, classUnderTest.getStars());
        System.out.println(ANSI_GREEN + "testConstructor() - test passed successfully" + ANSI_RESET);
    }

    @Test
    public void testToString() {
        Review classUnderTest = new Review("Mr. Critic", 5, "Tasty burritos and sandwiches!");
        assertEquals("Review { author: \"Mr. Critic\", stars: 5, body: \"Tasty burritos and sandwiches!\" }", classUnderTest.toString());
        System.out.println(ANSI_GREEN + "testToString() - test passed successfully" + ANSI_RESET);
    }

    @Test void testConstructorThrowsIllegalArgumentException() {
        assertThrows(IllegalArgumentException.class, () -> new Review("Invalid Stars", 6, "Tasty burritos and sandwiches!"));
        System.out.println(ANSI_GREEN + "testConstructorThrowsIllegalArgumentException() - test passed successfully" + ANSI_RESET);
    }

}
