/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testMainThrowsExceptionWithNoArguments() throws IOException {
        try {
            String[] args = {};
            App.main(args);
            // if the exception is not thrown, fail the test
            fail("Expected IllegalArgumentException to be thrown, but no exception was thrown.");
        } catch (IllegalArgumentException e) {
            // the exception was thrown, the test passes
        }
    }

    @Test
    public void testMainThrowsExceptionWithWrongNumberOfArguments() throws IOException {
        try {
            String[] args = {"file1.js", "file2.js"};
            App.main(args);
            // if the exception is not thrown, fail the test
            fail("Expected IllegalArgumentException to be thrown, but no exception was thrown.");
        } catch (IllegalArgumentException e) {
            // the exception was thrown, the test passes
        }
    }

    @Test
    public void testRunLinterNoErrors() throws Exception {
        Path path = Paths.get("src/main/resources/gates-no-errors.js").toAbsolutePath();
        List<String> errorMessages = App.runLinter(path);

        assertEquals(0, errorMessages.size());
    }

    @Test
    public void testRunLinterOneErrors() throws Exception {
        Path path = Paths.get("src/main/resources/gates-one-error.js").toAbsolutePath();
        List<String> errorMessages = App.runLinter(path);

        assertEquals(1, errorMessages.size());
        assertTrue(errorMessages.contains("Line 2: Missing semicolon.\n"));
    }

    @Test
    public void testRunLinterFewErrors() throws Exception {
        Path path = Paths.get("src/main/resources/gates-few-errors.js").toAbsolutePath();
        List<String> errorMessages = App.runLinter(path);

        assertEquals(3, errorMessages.size());
        assertTrue(errorMessages.contains("Line 3: Missing semicolon.\n"));
        assertTrue(errorMessages.contains("Line 5: Missing semicolon.\n"));
        assertTrue(errorMessages.contains("Line 11: Missing semicolon.\n"));
    }

    @Test
    public void testRunLinterManyErrors() throws Exception {
        Path path = Paths.get("src/main/resources/gates-many-errors.js").toAbsolutePath();
        List<String> errorMessages = App.runLinter(path);

        assertEquals(11, errorMessages.size());
        assertTrue(errorMessages.contains("Line 3: Missing semicolon.\n"));
        assertTrue(errorMessages.contains("Line 5: Missing semicolon.\n"));
        assertTrue(errorMessages.contains("Line 11: Missing semicolon.\n"));
        assertTrue(errorMessages.contains("Line 94: Missing semicolon.\n"));
        assertTrue(errorMessages.contains("Line 95: Missing semicolon.\n"));
        assertTrue(errorMessages.contains("Line 96: Missing semicolon.\n"));
        assertTrue(errorMessages.contains("Line 97: Missing semicolon.\n"));
        assertTrue(errorMessages.contains("Line 98: Missing semicolon.\n"));
        assertTrue(errorMessages.contains("Line 99: Missing semicolon.\n"));
        assertTrue(errorMessages.contains("Line 100: Missing semicolon.\n"));
        assertTrue(errorMessages.contains("Line 101: Missing semicolon.\n"));
    }

    @Test
    public void testRunLinterEmptyFile() throws Exception {
        Path path = Paths.get("src/main/resources/empty-file.js").toAbsolutePath();
        List<String> errorMessages = App.runLinter(path);

        assertEquals(0, errorMessages.size());
    }
}
